business_case:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: product-reliability-analyzer
      dataset: business_case  # This will be the default schema
      threads: 4
      timeout_seconds: 300
      location: us
      keyfile: /Users/jemzin/Github/credix-data-pipeline/secrets/credix-pipeline-key.json
      
    prod:
      type: bigquery
      method: service-account
      project: product-reliability-analyzer
      dataset: business_case
      threads: 4
      timeout_seconds: 300
      location: us
      keyfile: /Users/jemzin/Github/credix-data-pipeline/secrets/credix-pipeline-key.json
