business_case:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: product-reliability-analyzer
      dataset: business_case_bronze  # This will be the default schema
      threads: 4
      timeout_seconds: 300
      location: us
      keyfile: /app/secrets/service-account-key.json
      
    prod:
      type: bigquery
      method: service-account
      project: product-reliability-analyzer
      dataset: business_case_bronze
      threads: 4
      timeout_seconds: 300
      location: us
      keyfile: /app/secrets/service-account-key.json
