business_case:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: product-reliability-analyzer
      dataset: business_case
      threads: 4
      timeout_seconds: 300
      location: us
      keyfile: /Users/jemzin/Github/credix-pipeline-key.json
      
    prod:
      type: bigquery
      method: service-account
      project: product-reliability-analyzer
      dataset: business_case
      threads: 4
      timeout_seconds: 300
      location: us
      keyfile: /Users/jemzin/Github/credix-pipeline-key.json


business_case:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: product-reliability-analyzer
      dataset: business_case
      threads: 4
      timeout_seconds: 300
      location: us
      keyfile: /Users/jemzin/Github/credix-pipeline-key.json
      
    prod:
      type: bigquery
      method: service-account
      project: product-reliability-analyzer
      dataset: business_case
      threads: 4
      timeout_seconds: 300
      location: us
      keyfile: /Users/jemzin/Github/credix-pipeline-key.json

# elementary:
#   outputs:
#     default:
#       type: bigquery
#       method: service-account
#       keyfile: /Users/jemzin/Github/credix-pipeline-key.json

#       project: product-reliability-analyzer
#       dataset: business_case_elementary
#       threads: 4
#       location: us
#       priority: interactive