version: 2

models:
  - name: cnpj_ws
    description: "Raw transaction data from external sources"
    columns:
      - name: _loaded_at
        description: "Timestamp when data was loaded"
        # tests:
        #   - not_null
      - name: _source_table
        description: "Source table identifier"

  - name: cnpj_ws_clean
    description: "Cleaned and standardized transaction data"
    columns:
      - name: standardized_customer_id
        description: "Standardized customer identifier"
        # tests:
        #   - not_null
      - name: data_quality_flag
        description: "Data quality validation flag"
        # tests:
        #   - accepted_values:
        #       values: ['VALID']
      - name: parsed_transaction_date
        description: "Parsed transaction datetime"
        # tests:
        #   - not_null

  - name: cnpj_ws_metrics
    description: "Daily aggregated customer transaction metrics"
    columns:
      - name: standardized_customer_id
        description: "Customer identifier"
        # tests:
        #   - not_null
      - name: transaction_date
        description: "Transaction date"
        # tests:
        #   - not_null
      - name: total_transactions
        description: "Total number of transactions per customer per day"
        # tests:
        #   - not_null
        #   - dbt_utils.expression_is_true:
        #       expression: ">= 0"
      - name: total_amount
        description: "Total transaction amount per customer per day"
        # tests:
        #   - not_null

  - name: installments
    description: "Bronze layer installments data from PostgreSQL"
    columns:
      - name: asset_id
        description: "Unique asset identifier"
      - name: payment_status
        description: "Current payment status"
      - name: _loaded_at
        description: "Timestamp when data was loaded to bronze layer"

  - name: installments_clean
    description: "Silver layer cleaned installments data with calculated metrics"
    columns:
      - name: asset_id
        description: "Unique asset identifier"
      - name: payment_status
        description: "Current payment status (PAID, OVERDUE, PENDING)"
      - name: days_from_due_date
        description: "Days from due date (negative = early, positive = late)"
      - name: payment_variance
        description: "Difference between paid and expected amount"
      - name: has_missing_key_fields
        description: "Data quality flag for missing required fields"

  - name: company_payment_summary
    description: "Gold layer company-level payment analytics and risk scoring"
    columns:
      - name: buyer_tax_id
        description: "Company tax identifier"
      - name: payment_completion_rate
        description: "Percentage of installments paid"
      - name: avg_payment_days
        description: "Average days from due date for paid installments"
      - name: payment_tier
        description: "Risk tier (EXCELLENT, GOOD, FAIR, POOR, HIGH_RISK)"
      - name: risk_score
        description: "Numerical risk score (0-100, higher = better)"
      - name: total_expected_amount
        description: "Total expected payment amount across all installments"

  - name: payment_analytics_detailed
    description: "Gold layer transaction-level analytics with company context"
    columns:
      - name: asset_id
        description: "Unique asset identifier"
      - name: payment_behavior
        description: "Detailed payment behavior classification"
      - name: payment_size_category
        description: "Payment amount category (MICRO, SMALL, MEDIUM, LARGE, XLARGE)"
      - name: company_risk_category
        description: "Company risk category based on size and type"
      - name: geographic_tier
        description: "Geographic risk classification"
      - name: overall_data_quality
        description: "Combined data quality assessment"
