version: 2

sources:

  - name: business_case_temp
    description: "Temporary staging tables from Dagster pipeline"
    database: "{{ var('gcp_project') }}"
    schema: business_case_temp
    tables:
      - name: cnpj_ws
        identifier: "{{ var('temp_table_name', 'cnpj_ws') }}"
        description: "Temporary CNPJ data from PostgreSQL"
        meta:
          dagster:
            asset_key: ["cnpj_temp_table"]
            group: cnpj_pipeline
        columns:
          - name: share_capital
            description: "Company share capital"
          - name: company_size
            description: "Size classification of the company"
          - name: legal_nature
            description: "Legal nature of the company"
          - name: simples_option
            description: "Whether company opted for Simples taxation"
          - name: is_mei
            description: "Whether company is MEI (Individual Microentrepreneur)"
          - name: is_main_company
            description: "Whether this is the main company"
          - name: company_status
            description: "Current status of the company"
          - name: is_active
            description: "Whether company is active"
          - name: zipcode
            description: "Company zipcode"
          - name: main_cnae
            description: "Main CNAE (economic activity) code"
          - name: state
            description: "State where company is located"
          - name: uf
            description: "State abbreviation"
          - name: city
            description: "City where company is located"
          - name: created_at
            description: "Record creation timestamp"
          - name: updated_at
            description: "Record update timestamp"

      - name: installments
        description: "Temporary installments data from PostgreSQL"
        columns:
          - name: asset_id
            description: "Asset identifier"
          - name: invoice_id
            description: "Invoice identifier"
          - name: amount
            description: "Installment amount"
          - name: due_date
            description: "Due date of installment"
          - name: paid_date
            description: "Date when installment was paid"
          - name: status
            description: "Installment status"
          - name: installment_number
            description: "Installment sequence number"
          - name: total_installments
            description: "Total number of installments"
