version: 2

models:
  - name: cnpj_ws
    description: "Bronze layer companies data from CNPJ WS API"
    tests:
      - elementary.freshness_anomalies:
          timestamp_column: "updated_at"
          anomaly_sensitivity: 3         
          detection_period:
            period: day
            count: 1
    columns:
      - name: share_capital
        data_type: float64
      - name: company_size
        data_type: string
      - name: legal_nature
        data_type: string
      - name: simples_option
        data_type: boolean
      - name: is_mei
        data_type: boolean
      - name: is_main_company
        data_type: boolean
      - name: company_status
        data_type: string
        tests:
          - not_null
          - accepted_values:
              values: ['Ativa', 'Baixada', 'Suspensa', 'Inapta']
      - name: is_active
        data_type: boolean
      - name: zipcode
        data_type: string
        meta:
          pii: true
      - name: main_cnae
        data_type: string
      - name: state
        data_type: string
      - name: uf
        data_type: string
      - name: city
        data_type: string
      - name: created_at
        data_type: timestamp
      - name: updated_at
        data_type: timestamp
      - name: buyer_tax_id
        data_type: string
        tests:
          - not_null
          - unique
      - name: _loaded_at
        description: "Timestamp when data was loaded"
        tests:
          - not_null
      - name: _source_table
        description: "Source table identifier"

  - name: installments
    description: "Bronze layer installments data from PostgreSQL"
    columns:
      - name: asset_id
        data_type: string
      - name: invoice_id
        data_type: string
      - name: buyer_tax_id
        data_type: string
        tests:
          - not_null
      - name: original_amount_in_cents
        data_type: int64
      - name: expected_amount_in_cents
        data_type: int64
      - name: paid_amount_in_cents
        data_type: int64
      - name: due_date
        data_type: date
      - name: paid_date
        data_type: date
      - name: invoice_issue_date
        data_type: date
      - name: buyer_main_tax_id
        data_type: string
        tests:
          - not_null:
              severity: warn  # Set severity for this specific test
      - name: _loaded_at
        description: "Timestamp when data was loaded to bronze layer"
        tests:
          - not_null